config/routes.rb
Rails.application.routes.draw do
  

  get 'payment/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  root                          'landing_page#home'
  get       '/signup'      =>   'users#new'
  get       '/show'        =>   'users#id'
  get       '/login'        =>   'sessions#new'
  post      '/login'        =>   'sessions#create'
  delete    '/logout'       =>   'sessions#destroy'
  get                             'sessions/new'
  put       '/review/:id' => 'review#update', :as => 'update_art'
  resources :users
  resources :settings
  resources :watch
  resources :artworks do
    resources :bids
  end
  resources :bidview, only: [:index]
  
  resources :review
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :artworks 
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

	validates :name,  presence: true, length: { maximum: 50 }
	validates :phone,  presence: true, length: { maximum: 15 }
  	VALID_EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_secure_password
  	validates :password, presence: true, length: { minimum: 8 }                    


  	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def send_bid_notification_email(artwork, bid)
    UserMailer.bid_notification(self, artwork, bid).deliver_now
  end

  def send_outbid_notification_email(artwork)
    UserMailer.outbid_notification(self, artwork).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  

	  def show
    	if logged_in?
          begin
            @user = User.find(session[:user_id])
          rescue ActiveRecord::RecordNotFound => e
            @user = User.create(:name => "Nil", :email => "nil@nil.edu", :password => "nil", :phone => "nil")
          end
          @active = true
      end

      if @user.admin
        @artworks = Artwork.all
      else
        @artworks = Artwork.where(:userid => session[:user_id])
      end

      @style = params[:view_style]
      if (@style == nil) 
        @style = "block"
      end
      
      @sort = params[:sort_by]
      case @sort
        when 'highest'
          @artworksall = Artwork.where(:approved => true).order(max_bid: :desc)
        when 'lowest'
          @artworksall = Artwork.where(:approved => true).order(max_bid: :asc)
        when 'highestBN'
          @artworksall = Artwork.where(:approved => true).order(autowinprice: :desc)
        when 'lowestBN'
          @artworksall = Artwork.where(:approved => true).order(autowinprice: :asc)
        when 'recent'
          @artworksall = Artwork.where(:approved => true).order(created_at: :desc)
        else
          @artworksall = Artwork.where(:approved => true)
      end

      @artworksall = @artworksall.to_a
      @artworksall.each do |art|
        if art.won 
          @artworksall.delete(art)
        end
      end


      @hash = Hash.new
      @artworksall.each do |art|
        if art.watchlist != nil
          if art.watchlist.include? @user.id.to_s
            @hash[art.id] = true
          else
            @hash[art.id] = false
          end
        else
          @hash[art.id] = false
        end
      end
      
  	end 

  	def new
    	@user = User.new
  	end

  	def create
    	@user = User.new(user_params)
    	if @user.save
        @user.send_activation_email
        flash[:info] = "Please check your email to activate your account."
        redirect_to root_url
	    else
      		render 'new'
    	end
  	end

  	private

  	def user_params
      params.require(:user).permit(:name, :phone, :email, :password,
                                   :password_confirmation)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, id: 'name', class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.phone_field :phone, id: 'phone', class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, id: 'email', class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, id: 'password', class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, id: 'confirm', class: 'form-control' %>

      <%= f.submit "Create my account", id: 'signup_button', class: "btn btn-primary"
       %>
    <% end %>
  </div>
</div>
<br>
<div class="center">
  <%= link_to "Cancel", "/", class: "btn btn-primary" %>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
 	<head>
    	<title>Health4All Auction Site</title>
    	<%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    	<!-- <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
    	<%= csrf_meta_tags %>
    	<!--[if lt IE 9]>
      		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      		</script>
    	<![endif]-->
  	</head>
  	<body onload="startTime()">
<% if @active %>
		<h1>Hello, <%= @user.name %>!</h1>

		
	     	<% if !flash[:notice].blank? %>
			   <div class = "alert alert-info">
			      <%= flash[:notice] %>
			   </div>
			<% end %>

			<br/>

			<% if @user.admin %>
				<%= link_to "Review Submitted Artwork", url_for(:controller => :review, :action => :index), id: 'approve_artwork', class: "submit_but btn btn-success" %>
				<br />
			<% end %>
				<br/>
				<%= link_to "View Bid History", "/artworks/1/bids", id: 'view_bid_history', class: "submit_but btn btn-info" %>
				<br />

			

		  <div>
		  	<br/>
		  	<h1 id="countdown">00:00:00</h1>
		  </div>

		
		  <% if @style == "line" %>
			  <div class="table-responsive line-view">
	  			<table class="table table-vcenter">
	    			
			      	<thead>  
			      		<th>
			      			<%= link_to("/users/#{@user.id}?view_style=line") do %>
				      			<button type="button" class="btn btn-default">
								  <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
								</button>
								<%end%>
								<span>                    </span>
								<%= link_to("/users/#{@user.id}?view_style=block") do %>
								  <button type="button" class="btn btn-default" aria-label="Left Align">
								  <span class="glyphicon glyphicon-th-large " aria-hidden="true"></span>
								</button> 
								<% end %>
							
						</th>
			      		<th><div id="right-align">Sort by: <div class="dropdown">
							  <button class="btn btn-default dropdown-toggle" type="button" id="sort_by_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
							    Dropdown
							    <span class="caret"></span>
							  </button>
							  <ul class="dropdown-menu" aria-labelledby="sort_by_dropdown">
							    <li><a href="/users/<%=@user.id%>?view_style=line&sort_by=lowest">Lowest Bid</a></li>
							    <li><a href="/users/<%=@user.id%>?view_style=line&sort_by=highest">Highest Bid</a></li>
							    <li><a href="/users/<%=@user.id%>?view_style=line&sort_by=highestBN">Highest Buy Now</a></li>
							    <li><a href="/users/<%=@user.id%>?view_style=line&sort_by=lowestBN">Lowest Buy Now</a></li>
							    <li><a href="/users/<%=@user.id%>?view_style=line&sort_by=recent">Most Recent</a></li>
							    <li role="separator" class="divider"></li>
							    <li><a href="/users/<%=@user.id%>?view_style=line&sort_by=id">Default Sort</a></li>
							  </ul>
							</div>
						</div>
						</th>
			      	</thead>
				    <tbody>  

				     	 <% @artworksall.each do |artwork| %> 
				          <tr>
				            <td><img src="<%= artwork.attachment_url %>" id="displayed" /></td>
				            <td>
				            	<div class="btn-toolbar bidview-homepage-button" role="group" aria-label="...">
				            		 <span style="height: 34px;"class="label label-primary padded_button_block">Current bid: $<%= '%.2f' % artwork.max_bid%></span>
				                <%= link_to "More Details", "/artworks/#{artwork.id}", id: 'upload_button1', class: "btn btn-info padded_button" %>
				                
				                <% if @hash[artwork.id] %>
				                	<%= link_to "Unwatch Item", watch_path(:id => artwork.id), id: "watch_button", class: "btn btn-success padded_button" %></div></td>
				                <% else %>
				                	<%= link_to "Watch Item", watch_path(:id => artwork.id), id: "watch_button", class: "btn btn-success padded_button" %></div></td>
				                <% end %>
				            
				          </tr>
				         
				      	<% end %>

				   </tbody>
	  			</table>

	  			
			  </div>
			  <br/> <br/> <br/>
			<% else %>
					
			      			<div class="sort_buttons">
			      				<div class="sort_buttons">
					      			<%= link_to("/users/#{@user.id}?view_style=line") do %>
						      			<button type="button" class="btn btn-default">
										  <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
										</button>
									<%end%>
									<span>                    </span>
									<%= link_to("/users/#{@user.id}?view_style=block") do %>
										  <button type="button" class="btn btn-default" aria-label="Left Align">
										  <span class="glyphicon glyphicon-th-large " aria-hidden="true"></span>
										</button> 
									<% end %>
								</div>
								<div style="text-align: center;">Sort by: </div>
								<div class="dropdown">
								  <button class="btn btn-default dropdown-toggle" type="button" id="sort_by_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								    Dropdown
								    <span class="caret"></span>
								  </button>
								  <ul class="dropdown-menu" aria-labelledby="sort_by_dropdown">
								    <li><a href="/users/<%=@user.id%>?view_style=block&sort_by=lowest">Lowest Bid</a></li>
								    <li><a href="/users/<%=@user.id%>?view_style=block&sort_by=highest">Highest Bid</a></li>
								    <li><a href="/users/<%=@user.id%>?view_style=block&sort_by=highestBN">Highest Buy Now</a></li>
								    <li><a href="/users/<%=@user.id%>?view_style=block&sort_by=lowestBN">Lowest Buy Now</a></li>
								    <li><a href="/users/<%=@user.id%>?view_style=block&sort_by=recent">Most Recent</a></li>
								    <li role="separator" class="divider"></li>
								    <li><a href="/users/<%=@user.id%>?view_style=block&sort_by=id">Default Sort</a></li>
								  </ul>
								</div>

							</div>
							<br/>



				     	 	
							<div style="text-align: center;">
						    <% @artworksall.each_slice(2) do |artwork1, artwork2| %> 
						    	<div class="row row-container">
						    		<div class ="col-md-6">
							      		<img src="<%= artwork1.attachment_url %>" id="displayed"/><br/>
							            <div class="sort_buttons">
							            	<div class="btn-toolbar" role="group" aria-label="...">
							            		 <span style="height: 34px;"class="label label-primary padded_button_block">Current bid: $<%= '%.2f' % artwork1.max_bid%></span>
												<%= link_to "More Details", "/artworks/#{artwork1.id}", id: 'upload_button1', class: "btn btn-info padded_button_block" %>
							            		<span></span>
							            		<% if @hash[artwork1.id] %>
									            <%= link_to "Unwatch Item", watch_path(:id => artwork1.id), id: "watch_button", class: "btn btn-success padded_button_block" %>
									            <% else %>
									            	 <%= link_to "Watch Item", watch_path(:id => artwork1.id), id: "watch_button", class: "btn btn-success padded_button_block" %>
									            <% end %>
							        		</div>
							    		</div>
				          			</div>
									<% if artwork2 != nil %>
									<div class="col-md-6">
									     		<img src="<%= artwork2.attachment_url %>" id="displayed"/><br/>
									            	<div class="sort_buttons">
									            <div class="btn-toolbar" role="group" aria-label="...">
									            <span style="height: 34px;"class="label label-primary padded_button_block">Current bid: $<%= '%.2f' % artwork2.max_bid%></span>
												<%= link_to "More Details", "/artworks/#{artwork2.id}", id: 'upload_button1', class: "btn btn-info padded_button_block" %>
									           
									            <span></span>
									            <% if @hash[artwork2.id] %>
									            	<%= link_to "Unwatch Item", watch_path(:id => artwork2.id), id: "watch_button", class: "btn btn-success padded_button_block" %>
									            <% else %>
									            	 <%= link_to "Watch Item", watch_path(:id => artwork2.id), id: "watch_button", class: "btn btn-success padded_button_block" %>
									            <% end %>
									        </div></div>
								    </div>    
								    <% end %>
								</div>
				      		<% end %>	

				  			</div>
				  			


	  			
			  

			 

			
			<% end %>

			 <div class="sort_buttons">
	  				<br/>
	  				<br/>
	  				<p style="font-famiy: 'Courier New', 'Times New Roman'; text-align: center;">Interested in directly helping Health4All?</p>
	  				<%= link_to "Submit your own Artwork", url_for(:controller => :artworks, :action => :new), id: 'upload_button1', class: "btn btn-primary" %><span> </span>
				    <%= link_to "Donate to Health4All", "http://hlth4all.org/Donors", id: 'donate_button', class: "btn btn-primary" %>

	  			</div>

			
			<br />
			<br />

			<br/>
			<h3> Submitted art:</h3>

			<% if @artworks.size > 0 %>

			<table class = "table table-bordered table-striped">
			   <thead>
			      <tr>
			         <th>Name</th>
			         <th>Download Link</th>
			         <th>Description</th>
			         <th> </th>
			      </tr>
			   </thead>
			   
			   <tbody>
			      <% @artworks.each do |artwork| %>
			         
			         <tr>
			            <td><%= artwork.name %></td>
			            <td><%= link_to "Download Artwork", artwork.attachment_url %></td>
			            <td><%= artwork.description %></td>
			            <td><%= button_to "Delete #{artwork.name}",  artwork, method: :delete, id: "delete_#{artwork.name}", class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{artwork.name}?" %></td>
			         </tr>
			         
			      <% end %>
			   </tbody>
			   
			</table>

			<% else %>
				You have not submitted any artwork.
				<br/>
				<br/>
				
			<% end %>



			<br/><br/><br/>
	  	<% else %>
	      You must be logged in to view this page.
	  	<% end %>    
  	</body>

  	<script>
  		function startTime() {
		    var today = new Date();
		    var hours = today.getHours();
		    var m = today.getMinutes();
		    var s = today.getSeconds();
		    var ampm;
		    if (hours > 12) {
			    hours -= 12;
			    ampm = " PM";
			} else if (hours < 12)  {
			    ampm =" AM";
			} else {
				ampm = " PM";
			}
		    m = checkTime(m);
		    s = checkTime(s);
		    document.getElementById('countdown').innerHTML =
		    hours + ":" + m + ":" + s + " " + ampm;
		    var t = setTimeout(startTime, 500);
		}
		function checkTime(i) {
		    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
		    return i;
		}
	</script>

 </html>