config/routes.rb
Rails.application.routes.draw do
  

  get 'payment/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  root                          'landing_page#home'
  get       '/signup'      =>   'users#new'
  get       '/show'        =>   'users#id'
  get       '/login'        =>   'sessions#new'
  post      '/login'        =>   'sessions#create'
  delete    '/logout'       =>   'sessions#destroy'
  get                             'sessions/new'
  put       '/review/:id' => 'review#update', :as => 'update_art'
  resources :users
  resources :settings
  resources :watch
  resources :artworks do
    resources :bids
  end
  resources :bidview, only: [:index]
  
  resources :review
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def show
      begin
        if logged_in?
        	@user = User.find(params[:id])
        end
      rescue ActiveRecord::RecordNotFound => e
        flash[:danger] = "Something went wrong! Sorry, try again."
        redirect_to root_url
      end

      @artworks = Artwork.where(:approved => true)
  end

  def update
  	if logged_in?
      begin
  		  @user = User.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        flash[:danger] = "Something went wrong! Sorry, try again."
        redirect_to root_url
        return
      end
  		if @user.anon == nil
  			@flip = true
  		else
  			@flip = !@user.anon
  		end
  		redirect_to "/settings/#{@user.id}"
  		if @user.update_attribute(:anon, @flip)
  			flash[:success] = "Your anonymous mode has been changed!"
  		else
  			flash[:danger] = "Something went wrong! Sorry, try again."
  		end
  	end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/edit.html.erb
<% if logged_in? %>

<% else %>
	You need to login to view this page.
<% end %>

app/views/settings/show.html.erb
<% if logged_in? %>

<br/>
<br/>
	
	<hr>
	<br/>
	<div style="text-align: center;">
		<table class="table table-condensed table-nonfluid center-table">
			<thead>
			      <tr style="background-color: grey;">
			         <th></th>
			         <th></th>
			      </tr>
			      <tr>
			         <th></th>
			         <th></th>
			      </tr>
			</thead>
			<tbody>
				<tr>
					<td>Name</td>
					<td><%= @user.name %></td>
				</tr>
				<tr>
					<td>Phone Number</td>
					<td><%= @user.phone%></td>
				</tr>
				<tr>
					<td>E-mail</td>
					<td><%= @user.email%></td>
				</tr>
				<tr>
					<td>Anonymous Mode*</td>
					<% if @user.anon %>
						<td>Yes</td>
					<% else %>
						<td>No</td>
					<%end%>
				</tr>
				<tr>
					<td>Admin</td>
					<% if @user.admin %>
					<td>Yes</td>
					<% else %>
					<td>No</td>
					<%end%>
				</tr>
				<tr>
					<td>Account created</td>
					<td><%= @user.created_at %></td>
				</tr>

				<tr><td></td><td></td></tr>
				<tr><td></td><td></td></tr>
				<tr><td></td><td></td></tr>
				<tr><td style="font-weight: bold">Options</td><td></td></tr>
				<tr><td>Password</td><td><%= link_to "Reset Password", new_password_reset_path %></td></tr>
				<tr><td>Anonymous Mode</td><td><%= link_to "Change", "/settings/#{@user.id}", :method => :put, id: 'anon_mode' %></td></tr>
				<tr><td></td><td></td></tr>
				<tr style="background-color: grey;">
			         <td></td>
			         <td></td>
			    </tr>
			</tbody>

		</table>

	<br/>
	<br/>
		<%= link_to "Submit Payment For Items", "/payment/index", id: 'submit_payment', class: "submit_but btn btn-success" %>
	<br/>
	<br/>
	<br/>
	*When you bid, your name will be displayed on the item's detail page. Anonymous mode will conceal your identity.
	</div>
	<br/>

	<% if @user.admin %>
		<h2>Approved artwork and highest bid:</h2>
		<% if @artworks.size > 0 %>
			<div style="text-align: center">
				<table class="table table-condensed table-nonfluid center-table">
					<tr>
						<th>Art ID</th>
						<th>Name</th>
						<th>Highest Bidder</th>
						<th>Bid Amount</th>
						<th>Contact Number</th>
						<th>Email</th>
						<th>Autowin</th>
					</tr>
					<% @artworks.each do |art| %>
						<tr>
							<td><%=art.id%></td>
							<td><%=art.name%></td>
							<% if art.leadinguser == nil %>
								<td>N/A</td>
								<td><%= '$%.2f' % art.max_bid %></td>
								<td>N/A</td>
								<td>N/A</td>
								<td>No</td>
							<% else %>
								<td><%=User.find(art.leadinguser).name%></td>
								<td><%= '$%.2f' % art.max_bid %></td>
								<td><%=User.find(art.leadinguser).phone%></td>
								<td><%=User.find(art.leadinguser).email%></td>
								<% if art.won %>

									<td>Yes</td>
								<% else %>
									<td>No</td>
								<% end %>
							<% end %>
						</tr>
					<% end %>
				</table>
			</div>
		<% else %>
			No artwork has been approved.
		<% end %>
		
	<hr>

	<% end %>

<% else %>
	You must be logged in to view this page.

<% end %>

app/views/settings/update.html.erb
<% if logged_in? %>

<% else %>
	You need to login to view this page.
<% end %>